apiVersion: v2
name: o11y-otel
description: A Helm chart to create & configure collectors (for Metrics, Logs & Traces) using OpenTelemetry Operator, install node-exporter, kube-state-metrics exporter & backbox-exporter, configure service & servicemonitors for kubernetes components

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"
dependencies:
# cert manager must be manually installed because it has CRDs
- name: kube-state-metrics
  version: "5.16.4"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: kubeStateMetrics.enabled
- name: prometheus-node-exporter
  version: "4.31.0"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: nodeExporter.enabled
- name: prometheus-blackbox-exporter
  version: "8.12.0"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: blackboxExporter.enabled
