{{- if and .Values.kubeEtcd.enabled .Values.kubeEtcd.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "o11y-otel.fullname" . }}-kube-etcd
  labels:
    app: {{ template "o11y-otel.name" . }}-kube-etcd
    jobLabel: kube-etcd
{{ include "o11y-otel.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeEtcd.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeEtcd.service.targetPort }}
{{- if .Values.kubeEtcd.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeEtcd.service.selector }}
{{ toYaml .Values.kubeEtcd.service.selector | indent 4 }}
    {{- else}}
    component: etcd
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
