{{- if and .Values.kubeProxy.enabled .Values.kubeProxy.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "o11y-otel.fullname" . }}-kube-proxy
  namespace: {{ template "o11y-otel.namespace" . }}
  labels:
    app: {{ template "o11y-otel.name" . }}-kube-proxy
  {{- with .Values.kubeProxy.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ include "o11y-otel.labels" . | indent 4 }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: {{ template "o11y-otel.name" . }}-kube-proxy
      release: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    {{- if .Values.kubeProxy.serviceMonitor.interval }}
    interval: {{ .Values.kubeProxy.serviceMonitor.interval }}
    {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- if .Values.kubeProxy.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.kubeProxy.serviceMonitor.proxyUrl}}
    {{- end }}
    {{- if .Values.kubeProxy.serviceMonitor.https }}
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    {{- end}}
{{- if .Values.kubeProxy.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.kubeProxy.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.kubeProxy.serviceMonitor.relabelings }}
    relabelings:
{{ tpl (toYaml .Values.kubeProxy.serviceMonitor.relabelings | indent 4) . }}
{{- end }}
{{- end }}
