{{- if and .Values.kubeProxy.enabled .Values.kubeProxy.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "o11y-otel.fullname" . }}-kube-proxy
  labels:
    app: {{ template "o11y-otel.name" . }}-kube-proxy
    jobLabel: kube-proxy
{{ include "o11y-otel.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeProxy.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeProxy.service.targetPort }}
{{- if .Values.kubeProxy.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeProxy.service.selector }}
{{ toYaml .Values.kubeProxy.service.selector | indent 4 }}
    {{- else}}
    k8s-app: kube-proxy
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
